Added core_version_requirement lines to .info.yml files (d.o. issue 3151215)
pfrenssen/cas_mock_server pull request #19
Opened 2020-06-18 18:44 UTC by joeparsons

PR for [d.o. issue 3151215](https://www.drupal.org/project/cas_mock_server/issues/3151215).

2020-06-18 19:58 UTC, claudiu-cristea requested changes

2020-06-18 19:58 UTC, claudiu-cristea commented on cas_mock_server.info.yml
>  core: 8.x
Drupal 8.7 support is over, also for security fixes. We should drop it too. Who wants to run the module will have to pin on 8.x-1.0-alpha3

2020-06-18 19:58 UTC, claudiu-cristea commented on tests/modules/cas_mock_server_test/cas_mock_server_test.info.yml
>  core: 8.x
Same here.

2020-06-18 20:27 UTC, pfrenssen commented
I'm going to look into the test failure.

2020-06-18 20:36 UTC, pfrenssen commented
Test was missing a dependency on the user module which is introduced in CAS 8.x-1.7. See #20

2020-06-18 20:46 UTC, pfrenssen commented
Dropped the old style `core: 8.x` version requirement as suggested in https://www.drupal.org/docs/creating-custom-modules/let-drupal-know-about-your-module-with-an-infoyml-file

2020-06-18 20:54 UTC, pfrenssen commented
@claudiu-cristea do you want to approve?

I am planning on also running tests on PHP 7.4 in a separate PR, then tomorrow we can roll a new release with D9 support.

2020-06-19 05:28 UTC, claudiu-cristea approved these changes

2020-06-19 05:28 UTC, merged